version: '3.6'

services:
  elasticsearch:
    image: elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  pythonapp:
    image: sabinaku/optibrium_task:v3
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local




